#!/bin/sh

#  ci_post_clone.sh
#  xDrip4iOS — Xcode Cloud
#
#  Runs immediately after Xcode Cloud clones the repository, before Swift Package
#  dependencies are resolved and before the build starts.
#
#  What it does
#  ------------
#  Generates the (intentionally gitignored) `xDripConfigOverride.xcconfig` at the
#  repository root from environment variables you set on the Xcode Cloud workflow.
#  That file is pulled in by the last line of xdrip/xDrip.xcconfig:
#      #include? "../xDripConfigOverride.xcconfig"
#  so anything written here overrides the project defaults without committing it.
#
#  This lets one repository produce several side-by-side installable builds
#  (e.g. "normal", "left", "right") purely from per-workflow environment values,
#  with no project-file edits.
#
#  Environment variables (set them under: Xcode Cloud workflow > Environment)
#  -------------------------------------------------------------------------
#  XDRIP_DEVELOPMENT_TEAM  (recommended) 10-char Apple Developer Team ID. Drives
#                          the signing team and the bundle id prefix
#                          (com.<TEAM>.xdripswift...). If unset, the team in
#                          xdrip/xDrip.xcconfig is used.
#  XDRIP_BUNDLE_ID_SUFFIX  (optional) Appended to the main bundle identifier so a
#                          variant can install alongside the others, e.g. ".left"
#                          -> com.<TEAM>.xdripswift.left (all extensions/watch
#                          targets derive from it automatically). Leave unset for
#                          the normal build.
#  XDRIP_APP_NAME          (optional) Home-screen name for the variant, e.g.
#                          "xDrip L". Leave unset to keep the default name.
#
#  NOTE on app groups: the Loop/Trio app groups are deliberately left untouched
#  (group.com.<TEAM>.loopkit.LoopGroup / ...trio.trio-app-group). All variants
#  therefore share one data container — only one variant should actively share to
#  Loop/Trio at a time. This matches the "shared app group" setup chosen for these
#  side-by-side builds.

set -e

echo "=== xDrip4iOS Xcode Cloud post-clone hook ==="

# Xcode Cloud invokes ci_scripts from inside the ci_scripts/ directory; the repo
# root (where xDripConfigOverride.xcconfig is #include?-d from) is one level up.
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OVERRIDE_FILE="$REPO_ROOT/xDripConfigOverride.xcconfig"

# Start fresh every build.
echo "// Generated by ci_scripts/ci_post_clone.sh for Xcode Cloud — do not edit or commit." > "$OVERRIDE_FILE"

if [ -n "$XDRIP_DEVELOPMENT_TEAM" ]; then
    echo "Signing team        : $XDRIP_DEVELOPMENT_TEAM"
    printf 'XDRIP_DEVELOPMENT_TEAM = %s\n' "$XDRIP_DEVELOPMENT_TEAM" >> "$OVERRIDE_FILE"
    printf 'DEVELOPMENT_TEAM = %s\n'       "$XDRIP_DEVELOPMENT_TEAM" >> "$OVERRIDE_FILE"
else
    echo "Signing team        : (default from xdrip/xDrip.xcconfig)"
fi

if [ -n "$XDRIP_BUNDLE_ID_SUFFIX" ]; then
    echo "Bundle id suffix    : $XDRIP_BUNDLE_ID_SUFFIX"
    # Keep the com.<TEAM>.xdripswift prefix; just append the variant suffix.
    printf 'MAIN_APP_BUNDLE_IDENTIFIER = com.$(DEVELOPMENT_TEAM).xdripswift%s\n' "$XDRIP_BUNDLE_ID_SUFFIX" >> "$OVERRIDE_FILE"
else
    echo "Bundle id suffix    : (none — normal build)"
fi

if [ -n "$XDRIP_APP_NAME" ]; then
    echo "App display name    : $XDRIP_APP_NAME"
    printf 'MAIN_APP_DISPLAY_NAME = %s\n' "$XDRIP_APP_NAME" >> "$OVERRIDE_FILE"
else
    echo "App display name    : (default)"
fi

echo "--- generated xDripConfigOverride.xcconfig ---"
cat "$OVERRIDE_FILE"
echo "----------------------------------------------"
echo "=== post-clone hook complete ==="
